version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend/app:/usr/src/app
    command: flask run --host=0.0.0.0 --debugger --reload